FROM jamiemccarthy/empire4-server:latest

RUN apk update && apk add --no-cache ruby
ADD docker /app
WORKDIR /app
VOLUME ["/usr/local/etc/empire", "/usr/local/var/empire"]
ENV GAME_FILE=/app/game.yml
CMD ["/usr/bin/ruby", "-e", "/app/setup.rb"]
