FROM jamiemccarthy/empire4-server:latest

RUN apk add --no-cache ruby ruby-json && gem install --no-document --quiet safe_yaml
COPY docker/setup.rb /app/
WORKDIR /app
VOLUME ["/usr/local/var/empire"]
ENTRYPOINT ["/usr/bin/ruby", "/app/setup.rb"]
