#!/bin/sh

# TODO: import this file from the host instead of editing it in the container,
# which I guess means mounting it (could be readonly) somewhere and then
# using pconfig to write it into /usr/local/etc/empire/econfig.
# Also, come up with a catchier name than "empire_comprehensive_configuration"
vi /app/empire_comprehensive_configuration
/usr/local/sbin/pconfig /app/empire_comprehensive_configuration > /usr/local/etc/empire/econfig2
mv /usr/local/etc/empire/econfig2 /usr/local/etc/empire/econfig

# TODO: write a ruby script to parse these values out of the
# "empire_comprehensive_configuration" file, splitting it into several files.
FAIRLAND_NUM_CONTINENTS=10
FAIRLAND_CONTINENT_SIZE=30
/usr/local/sbin/files -f &&                                                          \
  /usr/local/sbin/fairland $FAIRLAND_NUM_CONTINENTS $FAIRLAND_CONTINENT_SIZE
# TODO: write a ruby script using PTY that runs here
# <https://ruby-doc.org/stdlib-2.4.2/libdoc/pty/rdoc/PTY.html>
# to run the server, connect to it (over ordinary socket, no need for client
# I don't think), log in as POGO/peter, change the POGO password per the
# config file, set players' names and passwords per the config file,
# "exec /app/newcap_script", and stop the server.
